### ISSUE TITLE
Incompatibility with jigsaw-configured project

### ISSUE THREAD

**Issue by tm-ms** [microstream-one/microstream#11]
Reported by CK:
When trying to use MicroStream with a simple JavaFX project based on JDK 12 and a jigsaw configuration file, there are class loading errors that cannot be circumvented.

**Comment by fh-ms** [comment]
Maybe multi release jar files are the solution:

https://www.baeldung.com/java-multi-release-jar

This could be used to provide implementations for different java versions as well.

**Comment by tm-ms** [comment]
Special case when using sun.misc.Unsafe:
If the project's module is the "unnamed", then no action is required.
However, when a project defines modules, every Unsafe-using module requires the following entry:

```
requires jdk.unsupported;
```
See https://stackoverflow.com/questions/42538750/unable-to-export-a-package-from-java-base-module

(taken from microstream-one/microstream-private#93)

**Comment by fh-ms** [comment]
To use MicroStream in a Java >= 9 project, the maven dependencies have to be on the classpath, not the modulepath. When on the classpath, the artifacts are automatically seen as the 'unnamed' module, which exports all packages.

If the project uses a module-info.java, it has to have the maven dependencies on the modulepath and the MicroStream dependencies have to be imported with require '...'; This causes the split package problem to impede the usage of the MicroStream libraries, because different artifacts export the same package. E.g. 'base' and 'persistence.binary' both export 'one.microstream.collections'.

So, currently the only solution is to put the Maven dependencies on the classpath, and to desist from using a module-info.java.

**Comment by fh-ms** [comment]
Found a working solution. Additional deployment of a multi-version fat-jar (one.microstream:all) with a generated module-info.java ensures jigsaw compatibility.

**Comment by zdenek-jonas** [comment]
https://examples.javacodegeeks.com/core-java/java-9-jigsaw-project-tutorial/
Durch diese project getested. 
Add dependency to Microstream, add as Required modul, add class to use it and compile. 
Works
