### ISSUE TITLE
AFS: Inventorization overkill

### ISSUE THREAD

**Issue by fh-ms** [microstream-one/microstream#143]
A storage written in a directory with a lot of content revealed another performance leak. The AFS seems to walk the complete directory tree upwards. It took ~10 minutes on my local machine in the temp directory. That raises the question if it is necessary to do that.

![image](https://user-images.githubusercontent.com/53050506/88552927-f372ab80-d024-11ea-88e8-3643bdd8cbda.png)

**Comment by fh-ms** [comment]
Further debugging shows that the complete directory structure is indeed walked through, which consumes too much time.
With the storage root beeing `C:\Users\FHABER~1\AppData\Local\Temp\storage` the complete sub-tree of `C:\Users` is visited.

**Comment by tm-ms** [comment]
I fixed this by calling inventorize only on demand with a lazy initialization flag.
Due to memory padding, this little flag costs 8 bytes of memory per ADirectory instance, but what can you do ...?

Since the actual physical inventory is only necessary for iterating items/directories/files, I added an ensureInventorized() in those methods. Should it turn out that any other (maybe future) logic should need the inventory, too, it simply has to call that method at the beginnen.

I also found and fixed a tiny counting bug in resolveDirectoryPath along the way.

**Comment by zdenek-jonas** [comment]
tested with visual VM...
