### ISSUE TITLE
BigDecimal as root does not load its value

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#21]
This test failed:

```
   @Test
    void bigDecimalTest() {
        BigDecimal type = new BigDecimal(456);
        BigDecimal loaded = new BigDecimal(0);
        saveAndReload(type, loaded);
        assertEquals(type, loaded, "BigDecimal");
    }
```

```
org.opentest4j.AssertionFailedError: BigDecimal ==> 
Expected :456
Actual   :0
```

I just create a BigDecimal with value 456. This object is saved as root and then loaded. After load is the value 0.

Other codes:

```
    <T> T saveAndReload(T original, T loaded) {
        storage = startStorage(original);
        storage.storeRoot();
        storage.shutdown();

        storage = startStorage(loaded);
        return loaded;
    }

    private EmbeddedStorageManager startStorage(Object root) {
        return  EmbeddedStorage.start(root, workDir);
    }
```

**Comment by tm-ms** [comment]
The problem is that BigDecimal is an immutable value type and an instance of it is used as a constant (specifically the custom root). Native handlers never update instances of value types to avoid destroying the value type's design. Hence, if a BigDecimal is initialized with value 0, it will always remain 0.
Strictly seen, creating a database with a immutable root with a value of 456 and another one with a value of 0 are two different cases that are not comparable.

However, there is still an inconsistency that is suppressed here:
The value 456 is stored as the database's root (the "whole" database) but initializing the database anew results in a root ("whole database") value of 0 without exception.

This is only a problem when using value type instances as roots. When they are a normally referenced part of an entity graph, new instances are properly created instead of an existing instance being (not!) updated.

A possible solution would be to use the update method for validation.
If an existing constant with the value of 0 is passed, but the value 456 is loaded, it is an inconsistency that should/must be reported via an exception.
The down side of this solution is that the validation code is completely unnecessary in the normal case of referencing a value type as a part of a graph instead of as a constant/root. No one uses value types as a root instance in practice, since that would limit the whole database to being a single value type value (e.g. a single BigDecimal or a single String, etc.). An unnecessary validation of an occasional BigDecimal would not mean much harm. But unnecessarily validating every String instance, from 1 character to thousands of millions, would have a significant impact on performance and that completely unnecessary in all real applications.

Another solution would be to forbid using immutable value types as root instances.

This, however, causes a lot of follow-up problems:
1.)
How to detect immutable value types?
For all known immutable value types, an explicit list could be compiled, but any value types beyond that would not be covered.
However, the actual deciding aspect is the type handler itself, since it decides if the update method does anything or not. So the decision would have to be based on the type handler, assuming it is implemented correctly and consistently (e.g. returning a value consistent to the update method in a newly introduced method `boolean isValueType()`.)

2.)
This would have to apply to all constants, not just the root instance, since root is just a special cased constant and the same problem could occur with constants, too.
However, it very often makes sense to use value type instances as constants. So throwing an exception when using them with a database is not a good idea.


This all gets pretty complicated pretty fast.

The initial design idea regarding value type constants was:
- They are instances that are completely defined by the application code, not by the database.
- They get stored normally to include their state in the database, for example so that exports include the state and hence get a "compleness" of data.
- But their state gets ignored loading since the application defines their state, not the database.

Mixing in the database state for application-defined constants might seem as the consistent thing to do, but in the end, it's just a big complication.
And one that has almost no relevance in practical use cases.

This topic is not irrelevant, but it is something for some point in the future.

**Comment by tm-ms** [comment]
This will be solved by the combination of microstream-one/microstream-private#194 and microstream-one/microstream-private#200.

**Comment by tm-ms** [comment]
Fixed. See comment in microstream-one/microstream-private#200.
