### ISSUE TITLE
Take 37ms to store a List<Long>

### ISSUE THREAD

**Issue by 54446776** [microstream-one/microstream#294]
```java
public class StoreList
{
  public static class SimpleRoot<T>
  {
    final T collection;

    public SimpleRoot(T collection)
    {
      this.collection = collection;
    }

  }

  public static void main(String[] args)
  {
    EmbeddedStorageManager storageManager = EmbeddedStorage.start(Paths.get("data_list"));

    final List<Long> list = new ArrayList<>();
    SimpleRoot<List<Long>> root = new SimpleRoot<>(list);
    storageManager.setRoot(root);
    storageManager.storeRoot();
    
    long i = 0;
    while (true) {
      list.add(i++);
    
      long start = System.currentTimeMillis();
      storageManager.store(list);
      System.out.println("storage time: "+System.currentTimeMillis() - start);
    }
  }
}
```

Average storage time is 37ms in my Mac Book Pro M1. Replace ArrayList with EqHashTable, storage performance is almost same.

**Comment by zdenek-jonas** [comment]
This Problem is based on another implementation of Mac OS flush:
https://bugs.openjdk.java.net/browse/JDK-8205162 which is slow under Java > 8
We have found this problem already and the fix is already merged in master:
https://github.com/microstream-one/microstream/pull/287

The new release of Microstream will have this fix.
When I tried now your code under our actual dev code on MacOS:
![image](https://user-images.githubusercontent.com/17253582/146162477-904abd90-7086-4906-893e-cc1e903b40e5.png)

**Comment by 54446776** [comment]
Thx for the quick reply. Waiting for the new version. When will be released?

**Comment by fh-ms** [comment]
The next major release is in April, maybe some patch releases in between.
But you can clone the repo and build it yourself anytime.

**Comment by zdenek-jonas** [comment]
I'm closing this Issue because the enhancement is already implemented. In case of further problems, you can reopen this Issue or create a new one for a different type of problem.
