### ISSUE TITLE
List gets corrupted after loading from disk

### ISSUE THREAD

**Issue by Sandared** [microstream-one/microstream#456]
## Environment Details
* MicroStream Version: 07.01.00-MS-GA<
* JDK version: openjdk 11.0.16 2022-07-19 LTS
* OS: Linux

## Describe the bug
I defined a datatype that has a `List<XYZ>` member variable. Initially this List was instantiated as an ArrayList with one element and stored.
Then we replaced this list (unfortunately) via `oldList = List.of(anotherElement)` and stored it again.
Internally List.of() uses an ImmutableList. 
Now when we load this list again from disk, there are 2 instead of 1 Objects in it. The first is "anotherElement" and the second is only shown as "Object" in the debugger.

I created a minimal example here: https://github.com/Sandared/microstream-experiments/blob/main/src/main/java/io/jatoms/ListExperiment.java

When this example is run two or more times, then the count of elements is at first 1, then 2 and then stays at two. Expected behavior would be either to stay at 1 or at some point throw an error, because of the different List datatypes.

**Comment by hg-ms** [comment]
Many thanks for the demo.

I was not able to reproduce the issue with JDK 11, but it is a known behavior with JDK 15 or greater.
See https://github.com/microstream-one/microstream/issues/244.
For JDK 17 we provide some special type-handlers for those immutable lists.
(https://docs.microstream.one/manual/storage/addendum/specialized-type-handlers.html)

**Comment by Sandared** [comment]
Thanks for the hint :) We got it fixed.

Strange thing is this behavior suddenly appeared during our unit tests. The same test code ran without errors last week. This week we suddenly got this error on different machines with different setups.

**Comment by Sandared** [comment]
A follow-up question regarding the specialized type handlers for immutable lists:
Is there any danger in using these on Java 11?
We are currently running on Java 11, but want to upgrade to Java 17 and now we are thinking about introducing those type handlers while we are still on 11. Is this possible? Or will this lead to errors?

**Comment by hg-ms** [comment]
The Handler will work with java 17 and later only because the package is compiled with java 17.
While using java 11 you can do without those handlers. But if you migrate to java 17 you must use those handlers.

The reason why you need that handler is a change in the java implementation of the immutable List and Set with one and two elements (java.util.ImmutableCollections.List12<E>). If that List12 contains only one element the Java 11 implementation sets the second value to “null”. Since Java 15(as far as I remember) the “null” is replaced by an special object “EMPYT” as a sentinel for the unused element. 

We can’t include those handlers by default as long as we need be Java 8 compatible, as java 8 has no List.of(). The same applies to Set12 case too.

**Comment by hg-ms** [comment]
closing as there are no more new questions
