### ISSUE TITLE
Java Module Definition Missing and Names not following official naming conventions

### ISSUE THREAD

**Issue by marcelbaumann** [microstream-one/microstream#5]
Did I correctly interpret your documentation under https://manual.docs.microstream.one/installation#modules that microstream library is delivered as a Java module?

1. The official maven download of storage-04.01.00-MS-GA.jar does **not** contain any **module-info.class** file and therefore does not support modules. Could it be a configuration error in your CI. _And also has no 'Automatic-Module-Name' in the MANIFEST file_.

1. It is strange to use components not following official Java guidelines. Additionally, potential collisions are possible if other developers also violate these conventions.

Could you release a version supporting modules as stated in your documentation?
Could you consider renaming your modules following the official Java conventions?

**Comment by fh-ms** [comment]
The modules in the installation chapter refer to maven modules. 

Due to limitations in package handling in the JMS, we had to find a different solution. We offer a single fat-jar for JMS projects, see https://manual.docs.microstream.one/data-store/faq/java-features#does-microstream-work-with-the-java-module-system-jigsaw
