### ISSUE TITLE
Configuration validation exceptions must tell validation rules/values

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#67]
Our Documentation in page:
https://manual.docs.microstream.one/data-store/configuration/properties
says:
Minimum file size in bytes of a storage file to avoid merging with other files during housekeeping. 
**Must be greater than 1, maximum is 2GB.**

_It should be there, which format should be used._ 

When i write: 500
I received: 
```one.microstream.storage.exceptions.StorageExceptionInvalidConfiguration: Invalid file size: 500```
_Why is this number invalid?_

When i write 10Mb
I received:
```java.lang.IllegalArgumentException: Nonsensical size limits: min file size = 10000000, max file size = 8388608```
_I would write: Min size limit cannot be higher as actual max size limit. This number has many '0', its hard to read it._

Ok, I write: 20000000
I received:
```one.microstream.storage.exceptions.StorageExceptionInvalidConfiguration: Invalid file size: 20000000```
_Why is this number invalid?_

I write: 5kb
dann passt.
(previous edit was from ZJ via my computer during a meeting)

**Comment by tm-ms** [comment]
This problem is split over two layers/projects: Core and EmbeddedConfiguration.

The "Nonsensical ..." point was a problem in the core project.
I have overhauled all component types of StorageConfiguration to perform proper validation with meaningful exception messages.

More specifically, the following types now have "Validation" sub-type using a unified pattern for validating parameters.
StorageChannelCountProvider
StorageHousekeepingController
StorageDataFileEvaluator
StorageEntityCacheEvaluator

The following types just check for non-null values, so I left them with simple notNull(...) checks:
StorageFileProvider
StorageBackupSetup

See next comment for the second aspect.

**Comment by tm-ms** [comment]
The other problems (with "Invalid file size") are located in the EmbeddedConfiguration project.
They are also technically wrong as far as I can see. The file bounds can have arbitrary values inside the minimum and maximum limit.
This has to be fixed there.
In order to prevent redundant validation code, the "Validation" sub types' methods described above can/should be used.

**Comment by fh-ms** [comment]
Adapted validators in EmbeddedConfiguration project.

**Comment by fh-ms** [comment]
> Ok, I write: 20000000
I received:
one.microstream.storage.exceptions.StorageExceptionInvalidConfiguration: Invalid file size: 20000000
Why is this number invalid?

File sizes without suffix are now interpreted as bytes.

**Comment by zdenek-jonas** [comment]
Retest: 
There are still something. 
I just define the smallestSizeOfDataFile setDataFileMinimumSize:
0: correct:
```
Specified file minimum size of 0 is not in the valid range of [1024, 2147483647].
```

2147483647: a little nonsense, the maximum size is given in negative numbers, and I did not specify it.
```
java.lang.IllegalArgumentException: Specified file maximum size of -2147483648 is smaller than the specified file minimum size of 2147483647.
```

**Comment by tm-ms** [comment]
There's a copy&paste error in the exception for the maximum size check:
```
// can technically never happen for now, but the max value might change
if(fileMaximumSize >= maximumFileSize())
{
	 // (17.02.2020 TM)EXCP: proper exception
	throw new IllegalArgumentException(
		"Specified file maximum size of " + fileMinimumSize
		+ " is not in the valid range of ["
		+ minimumFileSize() + ", " + maximumFileSize() + "]."
	);
}
```
However, since `fileMaximumSize` is an int and `maximumFileSize()` is hard-coded to `Integer.MAX_VALUE`, I fail to see how that exception can ever happen. Hence the comment.
No idea how `fileMinimumSize` could have become negative except if that value was passed by the user.

**Comment by fh-ms** [comment]
Fixed copy&paste error, and also parameter mixup in configuration layer.

**Comment by tm-ms** [comment]
Okay, I was confused: The exception message was about the "smaller" case, not the case I pasted the code snippet for.
Nevertheless, 2 points of stupidity on my part in the pasted code:
1.) `fileMinimumSize` must still be `fileMaximumSize` 
2.) ">=" is wrong. It must be ">".

edit: Ah, FH already fixed my stupidity before my comment.

**Comment by zdenek-jonas** [comment]
Ok, test successful.
