### ISSUE TITLE
Missing PersistenceTypeDictionary.ptd in backup directory

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#76]
After load XML configuration with backupDirectory, the file PersistenceTypeDictionary.ptd has been not created in backup dir. 

I have following xml file:
```
<?xml version="1.0" encoding="UTF-8"?>
<properties>
	<property name="backupDirectory" value="C://Users//ZDENEK~1//AppData//Local//Temp//junit8758453482108621550//backup"/>
</properties>
```

And this code snippet:
```
Configuration configuration = Configuration.LoadXml(configFilePath.toUri().toURL());
 Customer customer = CustomerGenerator.generateNewCustomer();
EmbeddedStorageManager storageManager = configuration.createEmbeddedStorageFoundation().createEmbeddedStorageManager(customer).start();
```
With this call the file PersistenceTypeDictionary.ptd has been not created in backup dir. 

When i called: 
```
EmbeddedStorageManager storageManager = configuration.setBaseDirectory(location.toString()).createEmbeddedStorageFoundation().createEmbeddedStorageManager(customer).start();
```
Then the file has been created.

So the behavior is: When i create store manager without define the baseDirectory,  the file PersistenceTypeDictionary.ptd has been not created in backup dir. 

The similar problem has been already mentioned in [Stack Overflow](https://stackoverflow.com/questions/59337745/missing-persistencetypedictionary-ptd-in-backup-directory). Unfortunately at that time without further information.

Update: After 18.02.2020
Is this file in backup directory not created at all. 

Main Method to test it:
```
    public static void main(String[] args) throws IOException, InterruptedException {
        Path location = new File("c:\\temp").toPath();

        Path configFilePath = location.resolve("backupDirectory.xml");
        Path backupLocation = location.resolve("backup");

        StringBuilder builder = new StringBuilder();
        builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        builder.append("<properties>\n");
        builder.append("\t<property name=\"backupDirectory\" value=\""+ backupLocation.toString().replace("\\","//") + "\"/>\n");
        builder.append("</properties>");

        FileUtils.writeStringToFile(configFilePath.toFile(),builder.toString(), "UTF-8");

        Customer customer = CustomerGenerator.generateNewCustomer();

        Configuration configuration = Configuration.LoadXml(configFilePath.toUri().toURL());

        EmbeddedStorageManager storageManager = configuration.setBaseDirectory(location.toString()).createEmbeddedStorageFoundation().createEmbeddedStorageManager(customer).start();
        //EmbeddedStorageManager storageManager = configuration.createEmbeddedStorageFoundation().createEmbeddedStorageManager(customer).start();
        //https://github.com/microstream-one/microstream-private/issues/227 test after fix

        Thread.sleep(5000);

        List<File> files = (List<File>) FileUtils.listFiles(backupLocation.toFile(), null, true);

        assertTrue(files.size() > 2, files.toString());

        storageManager.shutdown();
    }
```

**Comment by tm-ms** [comment]
I have tested the issue on the core level, without the configuration level, to narrow down the search.
I created and committed the simplified WiP test class `MainTestBackupStoringMinimal` and committed it to the master branch.
There, the type dictionary gets copied as expected.

So the cause is either in the configuration layer or a weird special case in the core layer.
A test to determine which one is the case is necessary for further investigation.

**Comment by zdenek-jonas** [comment]
The Problem appears also, when the baseDirectory is direct in xml defined.
```
<?xml version="1.0" encoding="UTF-8"?>
<properties>
	<property name="backupDirectory" value="C:\Users\ZDENEK~1\AppData\Local\Temp\junit5705755157897513036\backup"/>
	<property name="baseDirectory" value="C:\Users\ZDENEK~1\AppData\Local\Temp\junit5705755157897513036"/>
</properties>
```

**Comment by fh-ms** [comment]
It is reproducible without the configuration layer. If you add a custom type dictionary handler in `MainTestBackupStoringMinimal` the type dictionary isn't created in the backup directory. I don't know if this is supposed to work:

```java
static final EmbeddedStorageManager STORAGE = EmbeddedStorage
	.Foundation(
		Storage.ConfigurationBuilder()
		.setDataFileEvaluator(
			// just to make testing more convenient. Not necessary for the backup itself.
			Storage.DataFileEvaluator(1024, 2048, 0.7)
		)
		.setBackupSetup(
			// the only necessary part to activate and configure backupping.
			StorageBackupSetup.New(XIO.Path("storageBackup"))
		)
	)
	.onConnectionFoundation(cf -> cf.setTypeDictionaryIoHandler(PersistenceTypeDictionaryFileHandler.New(
		XIO.Path("storage", "myname.ptd")
	)))
	.start()
;
```

**Comment by tm-ms** [comment]
I investigated the new findings and its admittedly a little complicated, but in the end, there is a plain simple reason:
EmbeddedStorage#ConnectionFoundation(StorageConfiguration, PersistenceTypeEvaluator) does a little magic by hooking in a listening PersistenceTypeDictionaryIoHandler that backups (backs up?) the type dictionary whenever a change is written.

Of course, this wiring logic has to be moved into some internal place in the StorageConnectionFoundation (=PersistenceFoundation) instead of having it "magically" in a constructor-like method and if that is circumvented, the whole type dictionary listening is missing all of a sudden.

I will fix that.

**Comment by tm-ms** [comment]
My prior comment was confused.
The backup-hooking logic is in the constructing method for a StorageConnectionFoundation, not a StorageFoundation.
This makes a big difference:
The ConnectionFoundation must always contain parts derived from the Storage's configuration to maintain consistency.
Specifically the storage fileProvider and the type dictionary IO handler. Because both depend on the file paths configured in the storage's configuration.
To change that would mean to create internal inconsistencies between the lower level storage layer and the application-level persistence layer.

With the confusion cleared up and looking at the code example again, what this example does, is:
- setup the storage configuration
(from which the ConnectionFoundation is internally/implicitely derived with its file paths referrring to the storage configuration)
- then rewire the properly setup Connection foundation to forget its current type dictionary IO handler and use a new one.

The new one, of course, does not have the ties to the storage backup strategy that was setup internally.
It's the user saying "No, I want this part to be something different".
This is not a bug, it's the user explicitely turning off type dictionary backupping.
Albeit, admittedly, in a rather implicit way.

Currently, the type dictionary is always located in the directory specified in the storage configuration.
Having the option to specify a differing path would be a feature request. And, tbh, it would complicate things a lot for the user with little value gain.

**Comment by tm-ms** [comment]
Here an example on how to set the type dictionary name if not via retroactively hacking the ConnectionFoundation:

There's a StorageFileProvider.Builder where all details of the StorageFileProvider can be set:
```
EmbeddedStorage.Foundation(
	Storage.ConfigurationBuilder()
	.setStorageFileProvider(
		Storage.FileProviderBuilder()
		.setTypeDictionaryFileName("MyCustomNamedTypeDictionary.lol")
		.createFileProvider()
	)
	.setBackupSetup(
		StorageBackupSetup.New(XIO.Path("storageBackup"))
	)
)
```

**Comment by zdenek-jonas** [comment]
Test passed.
