### ISSUE TITLE
createPersistenceManager() throws NPE for missing Persister

### ISSUE THREAD

**Issue by m-stoer** [microstream-one/microstream#86]
I tried to use the PersistenceFoundation.**createPersistenceManager** method **without** explicitly **setting** a **Persister**. This **threw** a **NPE** as the **PersistenceManager.New** method **doesn't accept null pointers** for the persister field.

When looking at the PersistenceFoundation.ensurePersister method a comment can be seen hinting that the PersistenceManager itself is used if no Persister is defined (null). This can be achieved if the PersistenceManager.Default constructor is used directly but the PersistenceFoundation.createPersistenceManager uses the PersistenceManager.New method.

**Comment by tm-ms** [comment]
This was really only an oversight.
In the past, a non-null persister was mandatory, hence the check.
Then the logic was changed to ensure a non-null persister later on by either using an existing non-null persister reference or the PersistenceManager instance itself as a fallback.
So the notNull check was no longer necessary/correct.

It didn't turn up in the testing during development since I always only passed non-null persister references.

I removed the notNull check, so the false exception won't occur anymore.
